CREATE TABLE ICE_REQUESTS (
	ID int IDENTITY(1,1) PRIMARY KEY,
	REQ_ID nvarchar(40) NOT NULL,
	AGENT_NAME nvarchar(50) NOT NULL,
	REQUEST_DATE DATETIME NOT NULL,
	IS_COMMERCIAL bit DEFAULT 0,
	CONTRAGENT_CODE nvarchar(20) NOT NULL,
	SALE_POINT_CODE nvarchar(20) NOT NULL,
	STORE_HOUSE_CODE nvarchar(20) NOT NULL,
	PRODUCT_CODE nvarchar(30) NOT NULL,
	PRODUCT_PACKS_NUM float NOT NULL,
	PRODUCT_NUM int NOT NULL,
	COMMENT nvarchar(1000),
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);